/**
 * sd-build.ts
 *
 * Runs Style Dictionary against the generated token files and
 * writes the final combined tokens.css bundle.
 */

import StyleDictionary from 'style-dictionary';
import config from '../sd.config.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST = path.resolve(__dirname, '../dist');

const sd = new StyleDictionary({
  ...config,
  // Broken refs come from tag tokens that reference the _Layer contextual
  // collection (intentionally excluded). Warn instead of throwing.
  log: { errors: { brokenReferences: 'console' } },
});
await sd.buildAllPlatforms();

// Write the combined CSS bundle
const combined = `/**
 * @my-ds/tokens — Full Token Bundle
 * Auto-generated by Style Dictionary. Do not edit manually.
 */
@import './base.css';
@import './semantic-dark.css';
@import './typography.css';
`;
fs.writeFileSync(path.join(DIST, 'tokens.css'), combined, 'utf-8');
console.log('  ✓  tokens.css (combined bundle)');

// ─── src/ TypeScript codegen ─────────────────────────────────────────────────
// Generate base-colors.ts and semantic-colors.ts from the SD token JSON files
// so they stay in sync with the Figma export and use baseColors references.

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR  = path.join(ROOT, 'src');
const BASE_JSON = path.join(ROOT, 'tokens', 'base.json');
const COLOR_DARK_JSON = path.join(ROOT, 'tokens', 'color-dark.json');

type SDLeaf   = { $type: string; $value: unknown };
type SDBranch = Record<string, SDLeaf | SDBranch>;
type SDNode   = SDLeaf | SDBranch;

function isSdLeaf(node: SDNode): node is SDLeaf {
  return typeof node === 'object' && node !== null && '$type' in node;
}

/** "White 25%" → "white-25"  |  "10" → "10"  |  "White" → "white" */
function normalizeBaseKey(key: string): string {
  return key
    .toLowerCase()
    .replace(/\s*%\s*/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

/** kebab-case → camelCase */
function camelCase(s: string): string {
  return s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** Return a quoted key only if the identifier is not a plain JS identifier. */
function jsKey(raw: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(raw) ? raw : `'${raw}'`;
}

/**
 * Try to produce a baseColors / hoverColors reference from an SD alias string.
 * Returns null for literal values (rgba, hex, etc.).
 */
function baseColorRef(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const m = value.match(/^\{color\.(default|hover)\.([^.]+)\.(.+)\}$/);
  if (!m) return null;
  const [, section, palette, step] = m;
  const norm = normalizeBaseKey(step);
  const acc  = /^\d+$/.test(norm) ? `[${norm}]` : `['${norm}']`;
  const obj  = section === 'hover' ? 'hoverColors' : 'baseColors';
  return `${obj}.${palette}${acc}`;
}

// ── Generate src/base-colors.ts ─────────────────────────────────────────────

/** Emit a flat palette block as lines of `  key: value,` */
function emitPaletteBlock(tokens: SDBranch): string[] {
  return Object.entries(tokens).map(([key, tokenNode]) => {
    const norm  = normalizeBaseKey(key);
    const isNum = /^\d+$/.test(norm);
    const k = isNum ? norm : `'${norm}'`;
    const v = JSON.stringify((tokenNode as SDLeaf).$value);
    return `    ${k}: ${v},`;
  });
}

function generateBaseColors(): void {
  const baseJson = JSON.parse(fs.readFileSync(BASE_JSON, 'utf-8')) as SDBranch;
  const colorSections = baseJson.color as SDBranch;   // { default: {...}, hover: {...} }

  // Build one block array per section (default / hover)
  const sectionBlocks: Record<string, string[]> = {};

  for (const [sectionName, palettes] of Object.entries(colorSections)) {
    const blocks: string[] = [];
    for (const [palette, tokens] of Object.entries(palettes as SDBranch)) {
      const bar = '─'.repeat(Math.max(0, 68 - palette.length));
      blocks.push(
        `  // ─── ${palette} ${bar}\n  ${palette}: {\n${emitPaletteBlock(tokens as SDBranch).join('\n')}\n  },`
      );
    }
    sectionBlocks[sectionName] = blocks;
  }

  const defaultBlocks = sectionBlocks['default'] ?? [];
  const hoverBlocks   = sectionBlocks['hover']   ?? [];

  fs.writeFileSync(path.join(SRC_DIR, 'base-colors.ts'), `/**
 * Base Color Tokens
 * Primitive palette — auto-generated from Figma "Base" collection.
 *
 * ⚠️  Do NOT edit manually — re-run \`pnpm figma:sync && pnpm sd:build\` to regenerate.
 *     Do NOT reference these directly in components — use semantic tokens instead.
 */

/** Primitive colors — base palette values. */
export const baseColors = {
${defaultBlocks.join('\n\n')}
} as const;

/** Hover-state color overrides — use only for hover backgrounds. */
export const hoverColors = {
${hoverBlocks.join('\n\n')}
} as const;

export type BaseColor = typeof baseColors;
`, 'utf-8');
  console.log('  ✓  src/base-colors.ts');
}

// ── Generate src/semantic-colors.ts ─────────────────────────────────────────

const SKIP_SEMANTIC_GROUPS = new Set([
  'Transparent',
  'inverse White + Black',
  '_layer',
  '_layer accent',
  '_field',
  '_content switcher (low contrast)',
]);

/**
 * Strip any ancestor-group prefix from a token key so the object API is clean.
 *   text.text-default  → text.default
 *   tag.Blue.tag-background → tag.Blue.background
 *   icon._icon-on-color-disabled → icon.onColorDisabled
 *   focus.focus → focus.default
 */
function stripPrefix(key: string, ancestors: string[]): string {
  let k = key.startsWith('_') ? key.slice(1) : key;
  for (let i = ancestors.length - 1; i >= 0; i--) {
    const anc = ancestors[i];
    if (k === anc) return 'default';
    if (k.startsWith(`${anc}-`)) return k.slice(anc.length + 1);
  }
  return k;
}

function emitNode(node: SDNode, ancestors: string[], indent: string): string {
  if (isSdLeaf(node)) {
    const ref = baseColorRef(node.$value);
    return ref ?? JSON.stringify(node.$value);
  }

  const inner = indent + '  ';
  const lines: string[] = [];
  for (const [rawKey, child] of Object.entries(node as SDBranch)) {
    if (rawKey.startsWith('$')) continue;
    const stripped = stripPrefix(rawKey, ancestors);
    const k = jsKey(camelCase(stripped));
    lines.push(`${inner}${k}: ${emitNode(child, [...ancestors, rawKey], inner)}`);
  }
  return lines.length ? `{\n${lines.join(',\n')}\n${indent}}` : '{}';
}

function generateSemanticColors(): void {
  const colorDark = JSON.parse(fs.readFileSync(COLOR_DARK_JSON, 'utf-8')) as SDBranch;

  const groups: string[] = [];
  for (const [groupKey, groupNode] of Object.entries(colorDark)) {
    if (SKIP_SEMANTIC_GROUPS.has(groupKey)) continue;
    const gKey = jsKey(camelCase(groupKey));
    const val  = emitNode(groupNode as SDNode, [groupKey], '  ');
    const bar  = '─'.repeat(Math.max(0, 68 - groupKey.length));
    groups.push(`  // ─── ${groupKey} ${bar}\n  ${gKey}: ${val}`);
  }

  fs.writeFileSync(path.join(SRC_DIR, 'semantic-colors.ts'), `/**
 * Semantic Color Tokens — Dark Theme
 * Sourced from Figma "Color" collection, Dark mode.
 *
 * ⚠️  Auto-generated — do NOT edit manually.
 *     Re-run \`pnpm figma:sync && pnpm sd:build\` to regenerate.
 *
 * These tokens reference base colors by alias and are the
 * canonical tokens to use in components.
 */

import { baseColors, hoverColors } from './base-colors.js';

export const semanticColorsDark = {
${groups.join(',\n\n')}
} as const;

export type SemanticColors = typeof semanticColorsDark;
`, 'utf-8');
  console.log('  ✓  src/semantic-colors.ts');
}

// ── Generate src/dimension.ts ────────────────────────────────────────────────

function generateDimension(): void {
  const TOKENS = (p: string) => JSON.parse(fs.readFileSync(path.join(ROOT, 'tokens', p), 'utf-8'));

  const spacingJson    = TOKENS('spacing.json');
  const radiusJson     = TOKENS('radius.json');
  const typeScaleJson  = TOKENS('type-scale.json');
  const typeWeightJson = TOKENS('type-weight.json');
  const typoCozy       = TOKENS('typography-cozy.json');
  const typoCompact    = TOKENS('typography-compact.json');
  const baseJson       = JSON.parse(fs.readFileSync(BASE_JSON, 'utf-8')) as SDBranch;

  // Build resolution maps for aliases used inside typography
  const scaleMap: Record<string, number> = {};
  for (const [k, node] of Object.entries(typeScaleJson.typeScale as SDBranch))
    scaleMap[`typeScale.${k}`] = (node as SDLeaf).$value as number;

  const weightMap: Record<string, number> = {};
  for (const [k, node] of Object.entries(typeWeightJson.typeWeight as SDBranch))
    weightMap[`typeWeight.${k}`] = (node as SDLeaf).$value as number;

  // Base radius primitives for resolving semantic radius aliases
  const radiusPrimMap: Record<string, number> = {};
  const baseRadius = (baseJson as any).radius as SDBranch;
  if (baseRadius) {
    for (const [k, node] of Object.entries(baseRadius))
      radiusPrimMap[`radius.${k}`] = (node as SDLeaf).$value as number;
  }

  function resolveAlias(val: unknown): unknown {
    if (typeof val !== 'string' || !val.startsWith('{')) return val;
    const inner = val.slice(1, -1);
    return scaleMap[inner] ?? weightMap[inner] ?? radiusPrimMap[inner] ?? val;
  }

  // ── spacing ──
  const spacingLines: string[] = [];
  for (const [k, node] of Object.entries(spacingJson.spacing as SDBranch)) {
    const v = (node as SDLeaf).$value as number;
    spacingLines.push(`  '${k}': ${v},  // ${v}px`);
  }

  // ── radius (semantic) ──
  const radiusLines: string[] = [];
  for (const [k, node] of Object.entries(radiusJson.radiusSemantic as SDBranch)) {
    const raw = (node as SDLeaf).$value;
    const v   = resolveAlias(raw) as number;
    radiusLines.push(`  '${k}': ${v},`);
  }

  // ── typeScale ──
  const tsLines: string[] = [];
  const tsEntries = Object.entries(typeScaleJson.typeScale as SDBranch);
  for (let i = 0; i < tsEntries.length; i++) {
    const [k, node] = tsEntries[i];
    const v = (node as SDLeaf).$value as number;
    tsLines.push(`  'scale-${i}': ${v},  // ${k} — ${v}px`);
  }

  // ── typeWeight ──
  const twNames: Record<string, string> = {
    '100': 'thin', '200': 'extralight', '300': 'light', '400': 'regular',
    '500': 'medium', '600': 'semibold', '700': 'bold',
  };
  const twLines: string[] = [];
  for (const [k, node] of Object.entries(typeWeightJson.typeWeight as SDBranch)) {
    const v = (node as SDLeaf).$value as number;
    const name = twNames[k] ?? k;
    twLines.push(`  ${name}: ${v},`);
  }

  // ── typography builder ──
  function buildTypoLines(modes: Record<string, SDBranch>, modeKey: string): string[] {
    const styles = modes[modeKey] as Record<string, SDBranch>;
    const lines: string[] = [];
    for (const [styleName, props] of Object.entries(styles)) {
      const ff = resolveAlias((props.fontFamily as SDLeaf)?.$value);
      const fs_ = resolveAlias((props.fontSize as SDLeaf)?.$value) as number;
      const fw  = resolveAlias((props.fontWeight as SDLeaf)?.$value) as number;
      const lh  = resolveAlias((props.lineHeight as SDLeaf)?.$value) as number;
      const ls  = resolveAlias((props.letterSpacing as SDLeaf)?.$value) as number;

      const isNormal = ff === '{fontFamily.normal}' || ff === 'Inter';
      const ffLine   = isNormal ? '' : `    fontFamily: '${ff === '{fontFamily.mono}' || ff === 'IBM Plex Mono' ? 'mono' : ff}',\n`;
      const lsRound  = Math.round(ls * 1000) / 1000;

      lines.push(
        `  '${styleName}': {\n${ffLine}    fontSize: ${fs_},\n    fontWeight: ${fw},\n    lineHeight: ${lh},\n    letterSpacing: ${lsRound},\n  },`
      );
    }
    return lines;
  }

  const cozyLines   = buildTypoLines(typoCozy.typography   as Record<string, SDBranch>, 'cozy');
  const compactLines = buildTypoLines(typoCompact.typography as Record<string, SDBranch>, 'compact');

  fs.writeFileSync(path.join(SRC_DIR, 'dimension.ts'), `/**
 * Dimension, Typography & Scale Tokens
 *
 * ⚠️  Auto-generated — do NOT edit manually.
 *     Re-run \`pnpm figma:sync && pnpm sd:build\` to regenerate.
 */

/**
 * Spacing Tokens — Figma "Spacing" collection.
 */
export const spacing = {
${spacingLines.join('\n')}
} as const;

/**
 * Border Radius Tokens — Figma "Radius" collection (semantic aliases).
 */
export const radius = {
${radiusLines.join('\n')}
} as const;

/**
 * Type Scale Tokens — Figma "Type scale" collection (y₀–y₉ → scale-0–scale-9).
 */
export const typeScale = {
${tsLines.join('\n')}
} as const;

/**
 * Font Family Tokens — Figma "Font family" collection.
 * Fallback stacks are added here; the Figma export only contains the primary name.
 */
export const fontFamily = {
  normal: 'Inter, sans-serif',
  mono: '"IBM Plex Mono", monospace',
} as const;

/**
 * Font Weight Tokens — Figma "Type weight" collection.
 */
export const fontWeight = {
${twLines.join('\n')}
} as const;

/**
 * Typography Style Tokens — Cozy density (default).
 * Sourced from Figma "Typography styles" collection, Cozy mode.
 */
export const typography = {
${cozyLines.join('\n')}
} as const;

/**
 * Typography Style Tokens — Compact density.
 * Sourced from Figma "Typography styles" collection, Compact mode.
 */
export const typographyCompact = {
${compactLines.join('\n')}
} as const;

export type Spacing    = typeof spacing;
export type Radius     = typeof radius;
export type TypeScale  = typeof typeScale;
export type FontFamily = typeof fontFamily;
export type FontWeight = typeof fontWeight;
export type Typography = typeof typography;
export type TypographyCompact = typeof typographyCompact;
`, 'utf-8');
  console.log('  ✓  src/dimension.ts');
}

// Run codegen
console.log('\nsrc/ codegen');
generateBaseColors();
generateSemanticColors();
generateDimension();

console.log('\n✅  Style Dictionary build complete.');
