/**
 * Style Dictionary v4 configuration
 *
 * Source:  tokens/*.json  (generated by scripts/figma-to-sd.ts)
 * Output:  dist/
 *
 * Files generated:
 *   dist/base.css              — primitive CSS custom properties (:root)
 *   dist/semantic-dark.css     — semantic color tokens (dark theme)
 *   dist/typography.css        — typography custom properties (cozy + compact)
 *   dist/sd-tokens.js          — ESM JS tokens
 *   dist/sd-tokens.d.ts        — TypeScript declarations
 */

import StyleDictionary from 'style-dictionary';
import type { Config, TransformedToken } from 'style-dictionary/types';

// ─── Custom transforms ────────────────────────────────────────────────────────

// Emit dimension/number as "Npx" — skip typeWeight (unitless) and fontFamily (string)
StyleDictionary.registerTransform({
  name: 'ds/px',
  type: 'value',
  filter: (t: TransformedToken) =>
    (t.$type === 'dimension' || t.$type === 'number') &&
    typeof t.$value === 'number' &&
    t.path[0] !== 'typeWeight' &&
    t.path[t.path.length - 1] !== 'letterSpacing' &&
    // Within typography composites, font-weight sub-keys stay unitless
    !(t.path[0] === 'typography' && t.path[t.path.length - 1] === 'fontWeight'),
  transform: (t: TransformedToken) => (t.$value === 0 ? '0' : `${t.$value}px`),
});

// Round letter-spacing to 2 decimal places to avoid floating-point noise from Figma
StyleDictionary.registerTransform({
  name: 'ds/letter-spacing',
  type: 'value',
  filter: (t: TransformedToken) =>
    t.path[t.path.length - 1] === 'letterSpacing' && typeof t.$value === 'number',
  transform: (t: TransformedToken) => {
    const rounded = Math.round((t.$value as number) * 100) / 100;
    return rounded === 0 ? '0' : `${rounded}px`;
  },
});

StyleDictionary.registerTransformGroup({
  name: 'ds/css',
  transforms: ['attribute/cti', 'name/kebab', 'ds/px', 'ds/letter-spacing', 'color/css'],
});

StyleDictionary.registerTransformGroup({
  name: 'ds/js',
  transforms: ['attribute/cti', 'name/camel', 'color/css'],
});

// ─── Token path helpers ───────────────────────────────────────────────────────

const isPrimitive = (t: TransformedToken) =>
  t.path[0] === 'color' &&
  (t.path[1] === 'default' || t.path[1] === 'hover');

const isRadius = (t: TransformedToken) => t.path[0] === 'radius';

const isSemantic = (t: TransformedToken) =>
  !isPrimitive(t) && !isRadius(t) &&
  t.path[0] !== 'typography' &&
  t.path[0] !== 'typeScale' &&
  t.path[0] !== 'typeWeight' &&
  t.path[0] !== 'fontFamily' &&
  t.path[0] !== 'spacing' &&
  t.path[0] !== 'radiusSemantic' &&
  t.path[0] !== 'breakpoint';

const isTypography = (t: TransformedToken) => t.path[0] === 'typography';

// ─── Config ───────────────────────────────────────────────────────────────────

const config: Config = {
  // All generated token files — SD merges them into a single token tree
  source: [
    'tokens/base.json',
    'tokens/spacing.json',
    'tokens/radius.json',
    'tokens/type-scale.json',
    'tokens/font-family.json',
    'tokens/type-weight.json',
    'tokens/color-dark.json',
    'tokens/typography-cozy.json',
    'tokens/typography-compact.json',
    'tokens/breakpoint.json',
  ],

  platforms: {
    // ── CSS: base primitives ────────────────────────────────────────────────
    'css/base': {
      transformGroup: 'ds/css',
      prefix: 'ds',
      buildPath: 'dist/',
      files: [
        {
          destination: 'base.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: false,
          },
          filter: (t: TransformedToken) =>
            isPrimitive(t) ||
            isRadius(t) ||
            t.path[0] === 'spacing' ||
            t.path[0] === 'radiusSemantic' ||
            t.path[0] === 'typeScale' ||
            t.path[0] === 'fontFamily' ||
            t.path[0] === 'typeWeight' ||
            t.path[0] === 'breakpoint',
        },
      ],
    },

    // ── CSS: semantic dark ──────────────────────────────────────────────────
    'css/semantic-dark': {
      transformGroup: 'ds/css',
      prefix: 'ds',
      buildPath: 'dist/',
      files: [
        {
          destination: 'semantic-dark.css',
          format: 'css/variables',
          options: {
            selector: ':root, [data-theme="dark"]',
            outputReferences: true,
          },
          filter: isSemantic,
        },
      ],
    },

    // ── CSS: typography ─────────────────────────────────────────────────────
    'css/typography': {
      transformGroup: 'ds/css',
      prefix: 'ds',
      buildPath: 'dist/',
      files: [
        {
          destination: 'typography.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: true,
          },
          filter: (t: TransformedToken) =>
            isTypography(t) && t.path[1] === 'cozy',
        },
        {
          destination: 'typography-compact.css',
          format: 'css/variables',
          options: {
            selector: '[data-density="compact"]',
            outputReferences: true,
          },
          filter: (t: TransformedToken) =>
            isTypography(t) && t.path[1] === 'compact',
        },
      ],
    },

    // ── JS/TS ────────────────────────────────────────────────────────────────
    'js/tokens': {
      transformGroup: 'ds/js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'sd-tokens.js',
          format: 'javascript/esm',
          options: { outputReferences: false },
        },
      ],
    },
  },
};

export default config;
